version: '3.5'

services:
 keycloak:
   container_name: keycloak
   image: jboss/keycloak:9.0.2
   environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin
   ports:
     - "8089:8080"

 postgres:
   image: postgres:latest
   volumes:
     - pgdata:/var/lib/postgresql/data
   restart: always
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=bdpedido
   ports:
     - "5432:5432"
   networks:
     - network

 pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16544:80"
    networks:
      - network

 rabbitmq:
   image: rabbitmq:3-management-alpine
   container_name: 'rabbitmq'
   ports:
     - 5672:5672
     - 15672:15672
   volumes:
     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
   networks:
     - network

   # rabbitmq
   # usuario: guest
   # senha: guest

 mongo:
   ports:
     - '27017:27017'
   container_name: mongobd
   restart: always
   image: mongo

 mongo-express:
   container_name: mongo-express
   ports:
     - '8081:8081'
   image: mongo-express

 zookeeper:
   image: docker.io/bitnami/zookeeper:3
   ports:
     - "2181:2181"
   volumes:
     - "zookeeper_data:/bitnami"
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
   networks:
     - network

 kafka:
     image: docker.io/bitnami/kafka:2
     ports:
       - "9092:9092"
     volumes:
       - "kafka_data:/bitnami"
     environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
       - ALLOW_PLAINTEXT_LISTENER=yes
     depends_on:
       - zookeeper
     networks:
       - network

 redis:
   image: redis
   restart: always
   ports:
       - "6379:6379"
   volumes:
       - redis:/data
 redisinsight:
   image: redislabs/redisinsight:latest
   ports:
     - '8001:8001'

volumes:
  pgdata:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  redis:
    driver: local

networks:
  network:
    driver: bridge

